name: Cypress Test
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment Variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}"
          echo "GOOGLE_API_KEY=${{ secrets.VITE_GOOGLE_API_KEY }}"
          echo "PRUEBA=${{secrets.PRUEBA}}"
